namespace TestInterfaces {
    /// <summary>
    /// Database for all block IDs, taken from <see href="https://minecraft.fandom.com/wiki/Java_Edition_data_values/Classic"/>.
    /// </summary>
    public enum BlockId {
        Unknown = -1,
        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        WoodenPlank = 5,
        Sapling = 6,
        Bedrock = 7,
        Water = 8,
        Lava = 10,
        Sand = 12,
        Gravel = 13,
        GoldOre = 13,
        IronOre = 15,
        CoalOre = 16,
        Log = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        RedWool = 21,
        OrangeWool = 22,
        YellowWool = 23,
        LimeWool = 24,
        GreenWool = 25,
        AquaGreenWool = 26,
        CyanWool = 27,
        BlueWool = 28,
        PurpleWool = 29,
        IndigoWool = 30,
        VioletWool = 31,
        MagentaWool = 32,
        PinkWool = 33,
        BlackWool = 34,
        GrayWool = 35,
        WhiteWool = 36,
        Dandelion = 37,
        Rose = 38,
        BrownMushroom = 39,
        RedMushroom = 40,
        GoldBlock = 41,
        IronBlock = 42,
        Brick = 45,
        TNT = 46,
        Bookshelf = 47,
        MossyCobblestone = 48,
        Obsidian = 49,
    }
}